### ISSUE TITLE
possible boundary builder issue?

### ISSUE THREAD

**Issue by apiszcz** [evansiroky/timezone-boundary-builder#87] opened 2020-09-18 13:25 UTC
I am getting incorrect results when I use 
to combine and create ocean combined timezone
.\lib\timezonefinder\file_converter.py

Issue: https://github.com/MrMinimal64/timezonefinder/issues/107

Any thoughts on next steps to debug this?

Thanks.

**Comment by evansiroky** [comment] 2020-09-30 20:38
I checked the 2020a data and don't believe there would be any underlying problem with the data that would result in the problem you are seeing.

**Comment by apiszcz** [comment] 2020-10-01 01:05
Thanks, when I use timezonefinder without ocean zones it works correctly. Will give this feedback to MrMinimal64.

**Comment by evansiroky** [comment] 2020-11-05 22:22
Closing as this does not seem to be a problem caused by this project.

**Closed by evansiroky** 2020-11-05 22:22 UTC
